### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by spuder** [SimplyPrint/printer-ws-client#1]
I'm interested in using this library to integrate my 3d printer. 

Do you have any more documentation or examples? 

Questions I haven't been able to figure out

- How do I link the library to my account? 
- How do I name the printer?
- How do I define what features the printer supports? 
- Will the printer show up in the setup guide?

I'm sure I could figure it out with enough time. If you had any examples It would reduce the friction of implementation.

**Comment by spuder** [comment]
For example, I got the `virtual_printer.py` script running. However it appears to be connected to someone else's account. 

I'm _guessing_ the account is either defined in `config.json` or maybe is the uuid defined at `self.info.sentry_dsn = "https://a5aef1defa83433586dd0cf1c1fffe57@o1102514.ingest.sentry.io/6619552"`. 

However I'm not really sure beyond this how to integrate it with my account.

**Comment by cjavad** [comment]
Hi there Spuder its been almost 10 months since this issue was opened, we're closing this for now but the code base is now a lot more legible and in the future it is going to be super simple to integrate using this.
